import { s } from "@rippy/gateway-ez-mode";

/**
 * SBOR schemas for parsing Radix blockchain data
 * Generated from the Governance and VoteDelegation Scrypto blueprints
 *
 * Package address: package_rdx1p4p6x367f8z5cxyy382hfnnfwrdl900vh8l3fhnqzh7t9y00k4qc0t
 * Generated by: https://www.8arms1goal.com/sbor-ez-mode-ez-mode
 */

// =============================================================================
// Governance Component State
// =============================================================================

export const GovernanceParameters = s.struct({
  temperature_check_days: s.number(),
  temperature_check_quorum: s.decimal(),
  temperature_check_approval_threshold: s.decimal(),
  proposal_length_days: s.number(),
  proposal_quorum: s.decimal(),
  proposal_approval_threshold: s.decimal(),
});

export const Governance = s.struct({
  governance_parameters: GovernanceParameters,
  temperature_checks: s.internalAddress(), // KVS address
  temperature_check_count: s.number(),
  proposals: s.internalAddress(), // KVS address
  proposal_count: s.number(),
});

// =============================================================================
// Vote Types
// =============================================================================

export const TemperatureCheckVote = s.enum([
  { variant: "For", schema: s.tuple([]) },
  { variant: "Against", schema: s.tuple([]) },
]);

export const ProposalVoteOptionId = s.tuple([s.number()]);

// =============================================================================
// KVS Data Types
// =============================================================================

/**
 * File reference for on-chain file storage
 */
export const File = s.struct({
  kvs_address: s.string(),
  component_address: s.address(),
  file_hash: s.string(),
});

/**
 * Vote option definition
 */
export const ProposalVoteOption = s.struct({
  id: ProposalVoteOptionId,
  label: s.string(),
});

/**
 * Temperature Check stored in KVS
 */
export const TemperatureCheck = s.struct({
  title: s.string(),
  description: s.string(),
  vote_options: s.array(ProposalVoteOption),
  attachments: s.array(File),
  rfc_url: s.string(), // URL type maps to string
  quorum: s.decimal(),
  max_selections: s.option(s.number()),
  votes: s.internalAddress(), // KVS<Account, TemperatureCheckVote>
  approval_threshold: s.decimal(),
  start: s.instant(),
  deadline: s.instant(),
  elevated_proposal_id: s.option(s.number()),
});

/**
 * Proposal (RFP) stored in KVS
 */
export const Proposal = s.struct({
  title: s.string(),
  description: s.string(),
  vote_options: s.array(ProposalVoteOption),
  attachments: s.array(File),
  rfc_url: s.string(),
  quorum: s.decimal(),
  max_selections: s.option(s.number()),
  votes: s.internalAddress(), // KVS<Account, Vec<ProposalVoteOptionId>>
  approval_threshold: s.decimal(),
  start: s.instant(),
  deadline: s.instant(),
  temperature_check_id: s.number(),
});

// =============================================================================
// Vote Delegation Component State (for future use)
// =============================================================================

export const VoteDelegation = s.struct({
  delegatees: s.internalAddress(), // KVS address
  delegators: s.internalAddress(), // KVS address
});

export const Delegation = s.struct({
  delegatee: s.address(),
  fraction: s.decimal(),
  valid_until: s.instant(),
});

// =============================================================================
// Events
// =============================================================================

export const TemperatureCheckCreatedEvent = s.struct({
  temperature_check_id: s.number(),
  title: s.string(),
  start: s.instant(),
  deadline: s.instant(),
});

export const TemperatureCheckVotedEvent = s.struct({
  temperature_check_id: s.number(),
  account: s.address(),
  vote: TemperatureCheckVote,
});

export const ProposalCreatedEvent = s.struct({
  proposal_id: s.number(),
  temperature_check_id: s.number(),
  title: s.string(),
  start: s.instant(),
  deadline: s.instant(),
});

export const ProposalVotedEvent = s.struct({
  proposal_id: s.number(),
  account: s.address(),
  votes: s.array(ProposalVoteOptionId),
});

export const GovernanceParametersUpdatedEvent = s.struct({
  new_params: GovernanceParameters,
});

export const DelegationCreatedEvent = s.struct({
  delegator: s.address(),
  delegatee: s.address(),
  fraction: s.decimal(),
  valid_until: s.instant(),
});

export const DelegationRemovedEvent = s.struct({
  delegator: s.address(),
  delegatee: s.address(),
});

// =============================================================================
// Type Exports
// =============================================================================

export type GovernanceParametersType = ReturnType<
  typeof GovernanceParameters.parse
>;
export type GovernanceType = ReturnType<typeof Governance.parse>;
export type TemperatureCheckType = ReturnType<typeof TemperatureCheck.parse>;
export type ProposalType = ReturnType<typeof Proposal.parse>;
export type TemperatureCheckVoteType = ReturnType<
  typeof TemperatureCheckVote.parse
>;
export type ProposalVoteOptionIdType = ReturnType<
  typeof ProposalVoteOptionId.parse
>;
export type FileType = ReturnType<typeof File.parse>;
export type ProposalVoteOptionType = ReturnType<typeof ProposalVoteOption.parse>;
