import s from '@calamari-radix/sbor-ez-mode';
// Generated TypeScript schema for Scrypto SBOR types of package address: package_rdx1p4p6x367f8z5cxyy382hfnnfwrdl900vh8l3fhnqzh7t9y00k4qc0t
// Generated by: https://www.8arms1goal.com/sbor-ez-mode-ez-mode

export const VoteDelegation = s.struct({
  delegatees: s.internalAddress(),
  delegators: s.internalAddress()
});

export const TemperatureCheckVote = s.enum([
  { variant: "For", schema: s.tuple([]) },
  { variant: "Against", schema: s.tuple([]) }
]);

export const ProposalVoteOptionId = s.tuple([s.number()]);

export const DelegationRemovedEvent = s.struct({
  delegator: s.address(),
  delegatee: s.address()
});

export const GovernanceParameters = s.struct({
  temperature_check_days: s.number(),
  temperature_check_quorum: s.decimal(),
  temperature_check_approval_threshold: s.decimal(),
  proposal_length_days: s.number(),
  proposal_quorum: s.decimal(),
  proposal_approval_threshold: s.decimal()
});

export const GovernanceParametersUpdatedEvent = s.struct({
  new_params: GovernanceParameters
});

export const DelegationCreatedEvent = s.struct({
  delegator: s.address(),
  delegatee: s.address(),
  fraction: s.decimal(),
  valid_until: s.instant()
});

export const Governance = s.struct({
  governance_parameters: GovernanceParameters,
  temperature_checks: s.internalAddress(),
  temperature_check_count: s.number(),
  proposals: s.internalAddress(),
  proposal_count: s.number()
});

export const TemperatureCheckVotedEvent = s.struct({
  temperature_check_id: s.number(),
  account: s.address(),
  vote: TemperatureCheckVote
});

export const ProposalVotedEvent = s.struct({
  proposal_id: s.number(),
  account: s.address(),
  votes: s.array(ProposalVoteOptionId)
});

export const ProposalCreatedEvent = s.struct({
  proposal_id: s.number(),
  temperature_check_id: s.number(),
  title: s.string(),
  start: s.instant(),
  deadline: s.instant()
});

export const TemperatureCheckCreatedEvent = s.struct({
  temperature_check_id: s.number(),
  title: s.string(),
  start: s.instant(),
  deadline: s.instant()
});

